import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import PrimaryLayout from '@/components/layouts/primary/PrimaryLayout';
// import SideBarLayout from '@/components/layouts/sidebar/SideBarLayout';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Root layouts must contain html and body tags.
    <html lang="en">
      <body className={inter.className}>
        <PrimaryLayout>
          {children}
        </PrimaryLayout>  
      </body>
    </html>
  );
}
